# Generated by Django 4.2.13 on 2024-05-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection_app', '0002_remove_userprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_collection_app.userprofile'),
            preserve_default=False,
        ),
    ]
